src/components/BodyLogger.tsx
The problem was due to the fact that **the history object returned by useHistory is mutable**.
Internally, React Router DOM updates the history object without creating an entirely new one, this means that the reference of that object remains the same. That's the reason useEffect was not triggering on location change despite having history.location in the dependency array.
More info [here](https://v5.reactrouter.com/web/api/history/history-is-mutable)
=> PIN 1850 - Replaced useHistory with useLocation

src/components/Shared/AsyncTableEservice.tsx, src/hooks/useFeedback.tsx, src/views/EServiceRead.tsx, types.ts
This bug was due to the fact that in case an action needed a confirm dialog, the *runAction* function did not "await" the user confirmation but it synchronously just returned void.
```javascript
if (showConfirmDialog) {
wrapActionInDialog(runBasicAction, request.path.endpoint)
} else {
return await runBasicAction()
}
// returns void
```
So when an action with the confirmation dialog is fired it instantly resolves, without waiting for the actual async action to resolve.
This led to a crash inside *wrapCreateNewVersionDraft* function (*AsyncTableEservice.tsx*) due to an object decostruction on a function that returns void.
```javascript
const { outcome, response } = (await runAction(
...
```
---
The proposed solution transforms *wrapActionInDialog* in an async function that resolves only …
=> PIN - 1851 

public/locales/en/eservice.json, public/locales/it/eservice.json, src/components/InformationRow.tsx, src/components/Shared/EServiceContentInfo.tsx, src/views/EServiceManage.tsx, src/views/EServiceRead.tsx
This branch was created from the [pin-1704 branch](https://github.com/pagopa/pdnd-interop-frontend/tree/pin-1704).
Major changes:
- Brought UI redesign E-Service details ([PIN-1704](https://github.com/pagopa/pdnd-interop-frontend/pull/127)) in the subscriber context. 
- Added InformationRow **content container automatic adaptation** based on the type of its children ("div" if the children contains ReactNodes, else "p").
=> Pin 1932 - Redesign e-service details subscriber side

public/locales/en/eservice.json, public/locales/it/eservice.json, src/components/EServiceCreateStep2Version.tsx, src/components/Shared/AsyncTableEservice.tsx, src/components/Shared/StyledInputControlledSwitch.tsx, src/views/EServiceManage.tsx, types.ts
This PR solves breaking changes from [PIN-1769](https://pagopa.atlassian.net/browse/PIN-1769).
The `ESERVICE_VERSION_DRAFT_CREATE` api endpoint now requires ```agreementApprovalPolicy``` property.
- Added switch input field in step2 edit/create e-service for agreement policy selection
- Added a prop to ```StyledInputControlledSwitch``` to be able to show the Switch and the label in a horizontal layout.
- Added `agreementApprovalPolicy` property value to every `ESERVICE_VERSION_DRAFT_CREATE` api calls (defaults to _MANUAL_).
=> Pin 1764 - Agreement policy field

src/components/Shared/EServiceContentInfo.tsx, src/lib/env.ts, types.ts
`WELL_KNOWN_URL` env variable has been changed to `WELL_KNOWN_URLS`.
**NOTE**: `WELL_KNOWN_URLS` is now a comma separated list of urls but, for now, only the first url is shown
=> PIN-1971 - Updated WELL_KNOWN_URL env variable

public/locales/en/pagopa.json, public/locales/it/pagopa.json, src/components/BodyLogger.tsx, src/components/Shared/StyledTOSAgreementLayout.tsx, src/hooks/useTOSAgreementLocalStorage.ts, src/lib/constants.ts, src/views/TOSAgreement.tsx
- Added TOS agreement view. It block the render of all the private pages until the user accepts the TOS. The "acceptance" is represented by a record with `acceptTOS` as key inside _localStorage_.
- Added `LIGHT_GRAY` constants that contains the color "#FAFAFA".
=> Pin 1919 - TOS acceptance view

src/components/PurposeEditStep2RiskAnalysis.tsx, src/data/risk-analysis/pa/v2.0.json, src/hooks/useDynamicRiskAnalysisForm.tsx
In this PR the way FE and BE exchange Risk Analysis data has been changed to `Record<string, Array<string>>`.
- The function that maps all the questions before sending it to BE now transforms all the question values to array of string. 
- The function that takes all the fetched Risk Analysis data and put them into the Formik state has been changed to handle correctly the new data structure.
- Fixed a critical bug inside the logic of Risk Analysis 2.0 that rendered fields that were not supposed to be rendered
=> Pin 1939 - Updated FE risk analysis integration

src/components/Shared/StyledInputControlledAutocomplete.tsx, types.ts
The crash was due to the `StyledInputControlledAutocomplete` crashing when the internal state value null while the multiple prop is set to true. Internally MUI was trying to iterate on a null value.
Also, added property `consumer` to the `Client` type.
=> Pin 1903 - Fix crash on add client dialog render

src/components/VoucherReadStep1.tsx, src/lib/env.ts, types.ts
It is unused both by the frontend and the users trying to obtain a token
=> Removed M2M audience

public/locales/en/common.json, public/locales/en/toast.json, public/locales/it/common.json, public/locales/it/shared-components.json, public/locales/it/toast.json, src/components/EServiceCreateStep1General.tsx, src/components/Shared/AsyncTableAgreement.tsx, src/components/Shared/StyledDialog.tsx, src/components/Shared/StyledDialogRejectAgreement.tsx, src/config/api-endpoints.ts, src/lib/constants.ts, src/views/AgreementRead.tsx, types.ts
Implemented feature to reject agreement. When the "reject" button is clicked, a modal is opened. The provider must state the reason for rejecting the agreement and then submit the decision. A "REJECTED" status with an error color is added
=> Reject agreement

src/components/AttributeGroup.tsx
This PR updates the rendering logic of the declared attribute button.
It now appears only when the declared attribute is not `ACTIVE`.
=> Pin 2033 - Changed rendering logic of confirm declared attributes button

src/components/Shared/AsyncTableAgreement.tsx, src/views/AgreementRead.tsx
In this PR the delete agreement action is added to the menus in the agreement list and agreement read. The action is available ONLY when the agreement is `DRAFT` or `MISSING_CERTIFIED_ATTRIBUTES`.
=> PIN-2038  - Added delete agreement actions

public/locales/en/shared-components.json, public/locales/it/shared-components.json, src/components/Shared/DownloadableDocumentListSection.tsx, src/components/Shared/EServiceContentInfo.tsx, src/views/AgreementRead.tsx
In this PR the component `DownloadableDocumentListSection` has been generalized, making it usable outside the e-service context. It is now used inside the AgreementRead page to handle the agreement's documents.
=> PIN-2101 - Implemented download agreement documents

src/views/AgreementEdit.tsx
Logic for disabling/enabling submit button has been rewritten. 
The button will be always active if the id of the agreement's provider is the same as the id of the agreement's subscriber.
=> PIN-2075 - Submit agreement button must be always active if provider is the same as subscriber

public/locales/en/common.json, public/locales/it/common.json, src/components/MainNav.tsx, src/config/routes.ts, src/lib/env.ts, types.ts
This PR adds a new nav item to the sidenav that links to the selfcare's users page and removes the _API Operators_ page inside providers sub menu. Plus:
- Added _selfcareId_ property to _JwtUser_ model
=> PIN 2061 - Added external link to sidenav and removed "API Operators" page

src/config/i18n.ts
Disabled i18next escaping.
Not needed in React.
Related issue:
https://github.com/i18next/react-i18next/issues/277
=> PIN-2205 - Fixed i18n character escaping

src/api/react-query-wrappers.ts
This PR fixes the bug that did not allow the swap request to go through. The `react-query` queries are now disabled if the jwt token is falsy,
=> [FIX] - Added disabling query if jwt is falsy

package-lock.json, package.json, src/components/layout/containers/AttributeContainerRow.tsx, src/components/layout/containers/DocumentContainer.tsx, src/components/shared/DownloadableDocumentsList.tsx, src/config/env.ts, src/types/common.types.ts, vite.config.ts
This PR contains an improved way to test locally the application build.
On `npm run preview` command, a new developer build is created and served. 
The new developer build has a sourcemap, is not minified and takes the dev environment variable.
More changes:
- New command in package.json, `build-dev` allows to create a development build;
- Removed unused `AGREEMENT_PROCESS_URL` constant;
- `rollup-bundle-analyzer`'s html is no longer being generated on production build;
- Removed `icons-material` that are causing the application to crash. What causes the crash is still unknown;
- Updated packages `@pagopa/mui-italia` and `i18next`.
=> [PIN-2303] Refactor deployment fixes

src/hooks/useGetEServiceConsumerActions.ts, src/types/eservice.types.ts
This PR adapts the frontend to the backend change of the `canSubscribe` property being renamed `hasCertifiedAttributes`.
=> [PIN-2424] Renamed property type canSubscribe to hasCertifiedAttributes

package-lock.json, package.json, setupTests.js, src/api/comon.api.types.ts, src/api/eservice/eservice.hooks.ts, src/components/shared/Pagination.tsx, src/components/shared/__tests__/Pagination.test.tsx, src/components/shared/__tests__/__snapshots__/Pagination.test.tsx.snap, src/hooks/__tests__/usePagination.test.tsx, src/hooks/usePagination.ts, src/pages/ConsumerEServiceCatalogPage/ConsumerEServiceCatalog.page.tsx, src/pages/ConsumerEServiceCatalogPage/components/EServiceCatalogGrid.tsx
In this PR two pagination utilities has been added: 
- `@/components/shared/Pagination.tsx`, a component that renders the MUI's Pagination component only when there are more than 1 pages.
- `@/hooks/usePagination.ts`, contains all the logic needed for the pagination. Accepts Returns an object with three properties:
- `props` - an object with props to be passed to the `Pagination` component.
- `params` - an object with url param to be passed to the paginated service.
- `getTotalPageCount` - utility function that given the total records returns the total page count.
Also:
- 10dabef7eeeb41da2259e5db76655318311d3ebb - Pagination has been added to the e-service catalog page;
- b168a95710b3fe26a6a53ec45a5c02dbabc7a0d0 - Added global test mock to `window.scroll` function;
- …
=> [PIN-2301] Added pagination to e-service catalog page

src/api/eservice/eservice.hooks.ts, src/api/eservice/eservice.services.ts, src/pages/ProviderEServiceDetailsPage/ProviderEServiceDetails.page.tsx, src/pages/ProviderEServiceDetailsPage/hooks/__tests__/useGetEServiceProviderActions.test.tsx, src/pages/ProviderEServiceDetailsPage/hooks/useGetEServiceProviderActions.ts, src/pages/ProviderEServiceListPage/ProviderEServiceList.page.tsx, src/pages/ProviderEServiceListPage/components/EServiceTable.tsx, src/pages/ProviderEServiceListPage/components/EServiceTableRow.tsx, src/pages/ProviderEServiceListPage/hooks/__tests__/useGetProviderEServiceTableActions.test.tsx, src/pages/ProviderEServiceListPage/hooks/useGetProviderEServiceTableActions.ts, src/static/locales/en/common.json, src/static/locales/it/common.json
This PR changes the way producer's e-service are fetched and displayed.
The e-service are fetched trought the new BFF's API service /producers/eservices.
Pagination system is also implemented to the provider's e-service table.
NOTE:
This PR breaks the query invalidation for some services due to the new eventual consistency model implemented backend side.
=> [PIN-2299] - Redesign producer eservice page

src/api/attribute/attribute.services.ts, src/api/party/party.services.ts
All the `/institutions/` sub-paths in the BFF changed to `/tenants/`.
=> [PIN-2569] Updated institutions services paths

src/hooks/useActiveTab.ts, src/pages/ConsumerClientManagePage/components/VoucherInstructions/VoucherInstructions.tsx
Added the state containing the selectedPurposeId in URL instead of normal state to maintain the selectedPurpose during the navigation through the tabs (and pages)
=> [PIN-1905] - Added purpose memorization

src/pages/ConsumerClientManagePage/components/VoucherInstructions/VoucherInstructionsStep2.tsx, src/static/locales/en/client.json, src/static/locales/en/eservice.json, src/static/locales/en/mutations-feedback.json, src/static/locales/en/voucher.json, src/static/locales/it/client.json, src/static/locales/it/eservice.json, src/static/locales/it/mutations-feedback.json, src/static/locales/it/voucher.json
Replaced every "access token" string and localized string reference with "voucher". Only the "access token" in audience field in step-2 of e-service descriptor creation is standing
=> [PIN-2613] - Replaced "access token" strings with "voucher"

src/pages/ConsumerEServiceDetailsPage/ConsumerEServiceDetails.page.tsx
This PR fixes the rendering logic of the missing certified attributes alert.
The updated logic now renders the alert only when:
- the e-service is not owned by the active party;
- `descriptor.eservice.hasCertifiedAttributes` property is false;
- the actual viewing descriptor is the e-service active descriptor;
- the descriptor state is not "ARCHIVED". (It is not possible to have an active decriptor in "ARCHIVED" state right now, but it might be i the future)
=> [PIN-2658] - Fix missing certified attributes alert

src/hooks/__tests__/useActiveStep.test.tsx, src/hooks/useActiveStep.ts, src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/EServiceCreateStep1General.tsx, src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep2Version/EServiceCreateStep2Version.tsx
This PR adds tests for `useActiveStep` hook.
The way `useActiveStep` syncs with the location state has been changed. 
It does not sync with an useEffect, but with an initialization function inside the `activeStep` useState.
Added logic to the `back` function that does not allow the `activeStep` state to go below 0.
=> [PIN-2404] - Added useActiveStep hook testing

src/api/api.types.ts, src/api/eservice/eservice.api.types.ts, src/api/eservice/eservice.hooks.ts, src/api/eservice/eservice.services.ts, src/components/shared/ReactHookFormInputs/Autocomplete/AutocompleteMultiple.tsx, src/components/shared/ReactHookFormInputs/Autocomplete/AutocompleteSingle.tsx, src/components/shared/ReactHookFormInputs/Autocomplete/_AutocompleteBase.tsx, src/hooks/__tests__/useAutocompleteFilterInput.test.ts, src/hooks/__tests__/useQueryFilters.test.ts, src/hooks/useAutocompleteFilterInput.ts, src/hooks/useQueryFilters.ts, src/pages/ConsumerEServiceCatalogPage/ConsumerEServiceCatalog.page.tsx, src/pages/ConsumerEServiceCatalogPage/components/EServiceCatalogFilters.tsx, src/pages/ProviderEServiceListPage/ProviderEServiceList.page.tsx, src/pages/ProviderEServiceListPage/components/EServiceTableFilters.tsx, src/static/locales/en/eservice.json, src/static/locales/it/eservice.json, src/types/eservice.types.ts
This PR adds filter for the catalog and the provider's e-service table.
A hook that handles the filters, `useQueryFilters`, has been added.
Also:
- Fixed various problems with the MUI's autocomplete;
- Added `getProducers` and `getConsumers`services;
- Added tests for `useQueryFilters`.
=> [PIN-2228] e-service provider and catalog filters

__mocks__/data/purpose.mocks.ts, src/hooks/__tests__/useGetConsumerPurposesActions.test.ts, src/hooks/__tests__/useGetProviderPurposesActions.test.ts, src/hooks/useGetConsumerPurposesActions.ts, src/utils/__tests__/purpose.utils.test.ts, src/utils/purpose.utils.ts, src/utils/testing.utils.tsx
This PR adds testing for `useGetConsumerPurposesActions`, `useGetProviderPurposesActions` hooks and `purpose.utils.ts` file.
Also:
- Changed the way factory mocks function produces data, it now deep merges the passed data overwrite object.
=> [PIN-2744] - Purpose action hooks ad utils testing

src/api/eservice/eservice.services.ts, src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/EServiceCreateStep1General.tsx, src/static/locales/it/mutations-feedback.json
- Updated `postVersionDraftDocument` service url from `CATALOG_PROCESS` to `BACKEND_FOR_FRONTEND`;
- Fixed bug that prevented the e-service form to go forward on step 1 submit success;
- Updated suspend purpose service success feedback;
=> [PIN-2761] - Bug fixing test release

src/api/eservice/eservice.services.ts
This PR solves the issue [#271](https://github.com/pagopa/pdnd-interop-frontend/issues/271#issue-1587166916).
This PR changes the path from CATALOG to BFF to:
- `POST /eservices`
- `PUT /eservices/:eserviceId`
- `GET /eservices/:eserviceId/descriptors/:descriptorId/documents/:documentId`
- `DELETE /eservices/:eserviceId/descriptors/:descriptorId/documents/:documentId`
- `POST /eservices/:eserviceId/descriptors/:descriptorId/documents/:documentId/update`
=> [PIN-2781] - Update eservice services paths from CATALOG to BFF

src/components/shared/AgreementDetails/components/AgreementDocumentsListSection.tsx, src/types/agreement.types.ts
This PR removes the client logic that checks the presence of the contact for the agreement request.
The logic now it is handled backend side. The `isContractPresent` flag is exposed inside the get single agreement service.
=> [PIN-2849] - Added isContractPresent flag

src/config/axios.ts
This PR changes the way arrays are serialized to url params. 
From repeated param to comma separated param.
`{ param: ["a", "b"] }`
serializes from: 
`?param=a&param=b`
to:
`?param=a,b`
=> Feature: PIN-2878 - Updated url params serialization 

src/api/eservice/eservice.services.ts, src/hooks/__tests__/useGetProviderEServiceActions.test.ts, src/hooks/useGetProviderEServiceActions.ts
This PR brings the last CATALOG_PROCESS services to the BFF.
- `POST /eservices`
- `PUT /eservices/{eserviceId}`
- `DELETE /eservices/{eserviceId}`
- `POST /eservices/{eserviceId}/descriptors/{descriptorId}/clone`
- `DELETE /eservices/{eserviceId}/descriptors/{descriptorId}`
=> Feature: PIN-2781 - CATALOG_PROCESS to BFF

src/api/client/client.services.ts
Changed `getOperatorKeys` path from `${AUTHORIZATION_PROCESS_URL}/clients/${clientId}/operators/${operatorId}/keys` to `${BACKEND_FOR_FRONTEND_URL}/clients/${clientId}/relationships/${operatorId}/keys`
=> Feature: PIN-2905 - Changed getOperatorKeys path

src/api/client/client.services.ts, src/api/react-query-wrappers/__tests__/react-query-wrappers.utils.test.ts, src/api/react-query-wrappers/react-query-wrappers.utils.ts, src/api/react-query-wrappers/useMutationWrapper.ts, src/components/layout/Header.tsx, src/config/env.ts, src/hooks/__tests__/useGetClientActions.test.ts, src/hooks/__tests__/useResolveError.test.tsx, src/pages/ProviderEServiceDetailsPage/ProviderEServiceDetails.page.tsx, src/types/common.types.ts, src/utils/__tests__/common.utils.test.tsx
In this PR:
- Added `Area Riservata` product in the header's products selector;
- Removed unused `AUTHORIZATION_PROCESS` values;
- Fixes race-condition between route redirect and refetching logic that caused 404 BE errors when deleting a record from its details page;
- Removed "has draft descriptor" alert for non-admin users.
=> Feature: Area Riservata in header products selector and pre-release fixes

src/utils/__tests__/agreement.utils.test.ts, src/utils/agreement.utils.ts
This PR solves a bug where an agreement in REJECTED state was upgradable.
=> Feature: PIN-3375 -  Fix upgradable agreement with REJECTED state

src/components/shared/StepActions.tsx, src/components/shared/Stepper.tsx, src/components/shared/__tests__/__snapshots__/StepActions.test.tsx.snap, src/components/shared/__tests__/__snapshots__/Stepper.test.tsx.snap, src/components/shared/react-hook-form-inputs/RHFCheckboxGroup.tsx, src/components/shared/react-hook-form-inputs/RHFRadioGroup.tsx, src/components/shared/react-hook-form-inputs/__tests__/RHFCheckboxGroup.test.tsx, src/components/shared/react-hook-form-inputs/__tests__/RHFRadioGroup.test.tsx, src/components/shared/react-hook-form-inputs/__tests__/RHFTextField.test.tsx, src/components/shared/react-hook-form-inputs/__tests__/__snapshots__/RHFCheckboxGroup.test.tsx.snap, src/components/shared/react-hook-form-inputs/__tests__/__snapshots__/RHFRadioGroup.test.tsx.snap, src/components/shared/react-hook-form-inputs/__tests__/__snapshots__/RHFTextField.test.tsx.snap, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/RiskAnalysisForm.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/RiskAnalysisFormComponents.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/__tests__/RiskAnalysisForm.test.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/__tests__/__snapshots__/RiskAnalysisForm.test.tsx.snap, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/__tests__/__snapshots__/RiskAnalysisFormComponents.test.tsx.snap, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/components/RiskAnalysisFormSection.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/components/RiskAnalysisSwitch.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/components/__tests__/RiskAnalysisFormSection.test.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/components/__tests__/RiskAnalysisSwitch.test.tsx, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/components/__tests__/__snapshots__/RiskAnalysisFormSection.test.tsx.snap, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/RiskAnalysisForm/components/__tests__/__snapshots__/RiskAnalysisSwitch.test.tsx.snap, src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/__tests__/__snapshots__/PurposeEditStep2RiskAnalysis.test.tsx.snap, src/pages/ConsumerPurposeEditPage/utils/__tests__/risk-analysis-form.utils.test.ts, src/pages/ConsumerPurposeEditPage/utils/risk-analysis-form.utils.ts
- Implemented component `RiskAnalysisFormSection`
- Updated `RiskAnalysisFormComponents` with `RiskAnalysisFormSection` around all the input components
- Updated `RHFCheckboxGroup`, `RHFRadioGroup`, `RHFTextField` and `RiskAnalysisSwitch` setting the label optional
- Removed `backgroundColor` from `Stepper`
- Added new `justifyContent` prop to `StepActions`
- Separate `formatRiskAnalysisInputInfoLabel` into two functions (`formatRiskAnalysisInputInfoLabel`, `formatRiskAnalysisInputValidationInfoLabel`) that format the infoLabel and the validationInfoLabel
- Updated tests and snapshots
=> Feature: PIN-3484 - Redesign form analisi del rischio

src/hooks/useLoginAttempt.ts, src/pages/AssistanceTenantSelectionPage/AssistanceTenantSelection.page.tsx
The bug was caused by the `useLoginAttempt` hook removing the url fragment that is crucial to the team operations access flow. The fix is about checking first if the selfcare token is in the url fragment, if yes it can be removed safely.
=> Feature: Fix team operations access

src/utils/__tests__/attribute.utils.test.ts, src/utils/attribute.utils.ts
Removed the check of the verifier presence in the `revokedBy` array
=> Feature: Fixed check if verified attribute is revoked

src/pages/ConsumerClientManagePage/components/VoucherInstructions/VoucherInstructionsStep2.tsx, src/pages/ConsumerDebugVoucherPage/ConsumerDebugVoucher.page.tsx, src/pages/ConsumerDebugVoucherPage/__test__/__snapshots__/ConsumerDebugVoucher.page.test.tsx.snap, src/pages/ConsumerPurposeDetailsPage/components/PurposeDetailsTab/ConsumerPurposeDetailsGeneralInfoSection.tsx, src/pages/ConsumerPurposeDetailsPage/hooks/useGetPurposeStateAlertProps.ts, src/pages/ProviderAgreementDetailsPage/components/ProviderAgreementDetailsGeneralInfoSection/ProviderAgreementDetailsGeneralInfoSection.tsx, src/pages/ProviderPurposeDetailsPage/hooks/useGetPurposeStateAlertProps.ts
- Changed `Typography` variant from `body1` to `body2` in `VoucherInstructionsStep2`
- Added `Grid `with `xs=8` to `ConsumerDebugVoucher` page
- Fixed when warning alert apperared in ConsumerPurposeDetails page and ProviderPurposeDetails
- Replaced `IconLink` with `SectionContainer` bottomActions
- Updated snapshot
=> Feature: PIN-4181 - QA UI Frontend

src/api/purpose/purpose.services.ts, src/hooks/useGetConsumerPurposesActions.ts, src/pages/ConsumerAgreementCreatePage/components/ConsumerAgreementCreateAgreementGeneralInformation.tsx, src/pages/ConsumerClientManagePage/components/VoucherInstructions/VoucherInstructionsStep1/VoucherInstructionsStep1.tsx, src/pages/ConsumerPurposeDetailsPage/components/PurposeDetailsTab/ConsumerPurposeDetailsGeneralInfoSection.tsx, src/pages/OperatorDetailsPage/components/OperatorGeneralInfoSection.tsx, src/pages/ProviderPurposeDetailsPage/components/ProviderPurposeDetailsGeneralInfoSection.tsx
- Fix `downloadRiskAnalysisDocument` on `ConsumerPurposeDetailsGeneralInfoSection`
- Fix clone purpose adding payload
- Fix when `downloadRiskAnalysisDocument` bottomAction should be visible to the user
- Modified all bottomAction icons to have `fontSize="small"`
=> Hotfix: PIN-4333 - Fix section container bottom actions and purpose clone service function

src/pages/ConsumerPurposeDetailsPage/components/PurposeDetailsTab/ConsumerPurposeDetailsDailyCallsUpdateDrawer.tsx, src/static/locales/en/purpose.json, src/static/locales/it/purpose.json
- Added `currentVersion.dailyCalls` as default value in `ConsumerPurposeDetailsDailyCallsUpdateDrawer`
- Added validation for `dailyCalls` form value to be different from `currentVersion.dailyCalls`
- Added error strings
=> Feature: PIN-4331 - Fix bug same value error in ConsumerPurposeDetailsDailyCallsUpdateDrawer

src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceAutocomplete.tsx
- Changed `RHFAutocompleteSingle` name to solve the bug
- Added preselected eservice name in autocomplete
=> Fixed error during the eservice selection on purpose creation

src/components/layout/Header.tsx, src/components/layout/__tests__/__snapshots__/Header.test.tsx.snap, src/config/constants.ts, src/router/components/RoutesWrapper/__tests__/__snapshots__/RoutesWrapper.test.tsx.snap
- Modified `assistanceLink` to include `productId` based on `STAGE` variable
- Removed assistance button when the `STAGE` is different from `UAT` or `PROD`
- Updated snapshots
=> Feature: PIN-4580 - Add productId to self care assistance button

src/components/layout/Header.tsx, src/components/layout/SideNav/SideNav.tsx, src/config/constants.ts, src/config/env.ts, src/utils/common.utils.ts
This PR could have been done in several ways. I chose to have an object so that every time a new environment is created, the frontend is forced to update its config as well. This way, we are forced to set all the `STAGE` values that are allowed. 
`STAGE` values set to `QA` and `DEV` are actually irrelevant, they are there just to avoid breaking the UI, and a comment was put there to remind us
=> Fixed handling the current product in the PagoPA product selection dropdown

src/api/purpose/purpose.hooks.ts, src/components/dialogs/Dialog.tsx, src/components/dialogs/DialogClonePurpose/DialogClonePurpose.tsx, src/components/dialogs/DialogClonePurpose/DialogClonePurposeEServiceAutocomplete.tsx, src/hooks/__tests__/useGetConsumerPurposesActions.test.ts, src/hooks/useGetConsumerPurposesActions.ts, src/static/locales/en/mutations-feedback.json, src/static/locales/en/shared-components.json, src/static/locales/it/mutations-feedback.json, src/static/locales/it/shared-components.json, src/types/dialog.types.ts
- Implemented `DialogClonePurpose`
- Implemented `DialogClonePurposeEserviceAutocomplete`
- Implemented `DialogClonePurpose` management and when clone action has to be shown
- Added `DialogClonePurpose` props
- Added `DialogClonePurpose` strings
- Removed confirmation dialog and its strings from clone purpose
- Changed test
=> Feature: PIN-4017  - Update purpose clone dialog

src/hooks/__tests__/useGetProviderEServiceActions.test.ts, src/hooks/useGetProviderEServiceActions.ts, src/pages/ProviderEServiceSummaryPage/ProviderEServiceSummary.page.tsx
- Added new logic to delete eservice or descriptor draft in `useGetProviderEServiceActions`
- Added new logic to delete eservice or descriptor draft in `ProviderEServiceSummaryPage`
- Navigation for editing eservices in draft has been standardized. Now they always open summary and then open the eservice step if there is no description otherwise open descriptor step or riskAnalysis step (if mode RECEIVE) if there is a descriptor.
- Update test
=> Feature: PIN-4713-4714 - Implemented new logic to delete eservice or descriptor draft

src/api/auth/auth.hooks.ts, src/api/auth/auth.services.ts, src/api/auth/auth.utils.ts, src/components/layout/Header.tsx, src/components/layout/__tests__/__snapshots__/Header.test.tsx.snap, src/router/components/RoutesWrapper/__tests__/__snapshots__/RoutesWrapper.test.tsx.snap
This PR resolve issue about showing public pages. Several components stopped propagation to public pages because without JWT (or with expired jwt) some api calls get 401 so the app redirect user to LOGIN_PAGE though page didn't need token. 
Main changes:
1.  Removed use `useErrorBoundary` from `<Header/>` and added check on jwt
2. check if token is expired in `getSessionToken`
=> Bugfix: PIN-4746 - showing public pages if user isn't signed in

src/utils/__tests__/attribute.utils.test.ts, src/utils/attribute.utils.ts
This PR add a further control to check if attribute `(VERIFIED)` is owned or not. Now in addition to check if attribute is revoked or not, we check if it's expired.
=> Bugfix: PIN - 4816 - For attribute verified check if it's expired

package.json, src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceThresholdsSection.tsx, src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceUpdateThresholdsDrawer.tsx
- Fixed minutes to seconds conversion in drawer that updates the voucher duration
- Improved thousands formatting in threshold section
- Bumped version
=> Hotfix: Voucher duration update

src/pages/ConsumerAgreementDetailsPage/ConsumerAgreementDetails.page.tsx, src/pages/ConsumerAgreementDetailsPage/hooks/__test__/useGetConsumerAgreementAlertProps.test.ts, src/pages/ConsumerAgreementDetailsPage/hooks/useGetConsumerAgreementAlertProps.ts, src/static/locales/en/agreement.json, src/static/locales/it/agreement.json
- Updated `Alert` in `ConsumerAgreementDetailsPage`
- Implemented hook `useGetConsumerAgreementAlertProps` that have the business logic to show the correct alert
=> Feature: PIN-4604 - Implementing alert no purposes in agreement

src/router/routes.tsx
- Added `support` in `SUBSCRIBE_CLIENT_OPERATOR_EDIT` and  `SUBSCRIBE_INTEROP_M2M_CLIENT_OPERATOR_EDIT` routes `authLevels`
=> Feature: PIN-4849 - bug support cannot visualize the OperatorDetailsPage

src/components/layout/SideNav/hooks/__tests__/useGetSideNavItems.test.ts, src/components/layout/SideNav/hooks/useGetSideNavItems.ts, src/router/components/RoutesWrapper/AuthGuard.tsx, src/router/components/RoutesWrapper/__tests__/AuthGuard.test.tsx
- Added check in useGetSideNavItems to hide delegation section
- Added isUserAllowedToAccessDelegationsRoutes in AuthGuard.tsx
=> fix-hide-delegation-section-to-noPA-organizations

src/api/tenant/tenant.mutations.ts, src/api/tenant/tenant.services.ts, src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityDrawer.tsx, src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityTab.tsx, src/static/locales/en/mutations-feedback.json, src/static/locales/it/mutations-feedback.json, src/utils/__tests__/tenant.utils.test.ts, src/utils/tenant.utils.ts
- Implemented new services and mutations
- Update `tenant.utils`
- Update `DelegationAvailabilityDrawer`
- Update `DelegationAvailabilityTab`
=> Feature: PIN-5823 - delegated availability

src/pages/ProviderAgreementDetailsPage/ProviderAgreementDetails.page.tsx, src/pages/ProviderAgreementDetailsPage/components/ProviderAgreementDetailsGeneralInfoSection/ProviderAgreementDetailsContactDrawer.tsx, src/pages/ProviderAgreementDetailsPage/components/ProviderAgreementDetailsGeneralInfoSection/ProviderAgreementDetailsGeneralInfoSection.tsx, src/pages/ProviderAgreementsListPage/components/ProviderAgreementsTableRow.tsx, src/static/locales/en/agreement.json, src/static/locales/it/agreement.json
- Update `ProviderAgreementDetailsContactDrawer`
- Add delegated info
- Fix `ByDelegationChip` check for `ProviderAgreementsTableRow`
- Add strings
=> Feature: PIN-5827 - Delegated agreement producer management

src/pages/ProviderEServiceSummaryPage/ProviderEServiceSummary.page.tsx, src/router/routes.tsx
- Added `support` in `PROVIDE_ESERVICE_SUMMARY` route `authLevels`
=> Feature: PIN-4965 - bug support cannot visualize the eservice summary page

src/components/shared/react-hook-form-inputs/RHFTextField.tsx, src/components/shared/react-hook-form-inputs/__tests__/RHFTextField.test.tsx
This PR remove a @ts-ignore previous added in order to have `useFieldArray`() hook (react-hook-form) to work with our component.
Based on availability of props `indexFieldArray` and `fieldArrayKeyName` props, RHFTextField understand how to retrieve errors (if it's occur). This is placed inside useMemo to avoid unnecessary rendering. Also it's been introduced two new test in order to verifying this behaviour
=> Refactor/PIN-6484: remove @ts-ignore and refactor errors handling on RHFTextField

src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientPublicKeys.tsx, src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientPublicKeysTable.tsx, src/pages/ConsumerClientManagePage/components/VoucherInstructions/VoucherInstructionsStep1/VoucherInstructionsStep1.tsx
This ticket follow changing of API's behaviour ([PIN-4605](https://pagopa.atlassian.net/browse/PIN-4605)). In FE has been introduced pagination for the listing of public keys.
[PIN-4605]: https://pagopa.atlassian.net/browse/PIN-4605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIN-6528: Added pagination for ClientPublicKeys
