pagopa/pdnd-interop-frontend

- src/App.tsx
- src/__mocks__/providers.tsx
- src/components/BodyLogger.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/LangSwitch.tsx
- src/components/UserActionsSelect.tsx
- src/config/labels.ts
- src/hooks/useUser.ts
- src/lib/constants.ts
- src/lib/context.ts
- src/lib/jwt-utils.ts
- src/lib/router-utils.ts
- types.ts
Refactored header and footer so that they can be extracted in MUI. In this PR types are temporarily duplicated and some properties are commented. This is intentional as these components will soon be replaced with the ones integrated with other PagoPA products
> Extract common components

- .env
- src/components/AuthGuard.tsx
- src/components/BodyLogger.tsx
- src/components/PartySelect.tsx
- src/components/Shared/__tests__/__snapshots__/StepActions.tsx.snap
- src/components/Shared/__tests__/__snapshots__/StyledBreadcrumbs-test.tsx.snap
- src/components/Shared/__tests__/__snapshots__/StyledButton-test.tsx.snap
- src/components/Shared/__tests__/__snapshots__/StyledLink-test.tsx.snap
- src/config/api-endpoints.ts
- src/hooks/__tests__/useLogin-test.tsx
- src/hooks/useLogin.ts
- src/hooks/useParties.ts
- src/lib/api-interceptors-utils.ts
- src/lib/constants.ts
- src/lib/router-utils.ts
- src/views/ChooseParty.tsx
- src/views/Logout.tsx
- types.ts
Reverts pagopa/pdnd-interop-frontend#55
It will have to be merged after the last release of UAT, so I'm reverting this now
> Revert "Done token exchange integration with self-care"

- public/locales/en/agreement.json
- public/locales/en/common.json
- public/locales/en/toast.json
- public/locales/it/agreement.json
- public/locales/it/common.json
- public/locales/it/toast.json
- src/__mocks__/agreement.ts
- src/components/EServiceAttributeGroup.tsx
- src/components/EServiceCreateStep1General.tsx
- src/components/Shared/AsyncTableAgreement.tsx
- src/components/Shared/AsyncTableEservice.tsx
- src/config/api-endpoints.ts
- src/lib/constants.ts
- src/views/AgreementEdit.tsx
- src/views/EServiceRead.tsx
- types.ts
- Upgrade agreement lifecycle to new business logic
- Moved enpoints from agreement-process to backend-for-frontend
- Fixed minor bugs (logic to upgrade agreement, show upgrade agreement modal, fix secondsToMinutes conversion for e-service)
> Pin 1830 – Upgraded Agreement lifecycle

- public/locales/en/eservice.json
- public/locales/en/shared-components.json
- public/locales/it/eservice.json
- public/locales/it/shared-components.json
- src/components/EServiceAttributeGroup.tsx
- src/components/EServiceAttributeSection.tsx
- src/components/EServiceCreateStep1General.tsx
- src/components/Shared/StyledDialog.tsx
- src/components/Shared/StyledDialogAttributeDetails.tsx
- src/components/Shared/StyledInputControlledAsyncAutocomplete.tsx
- types.ts
- Updated UI/UX attribute selection in create e-service form
- Deleted *close* property in StyledInputProps type, updated all the *setDialog* calls
- Added *variant* prop in StyledInputControlledAsyncAutocomplete
> Pin 1809 - Redesigned attribute selection in create e-service form

- package.json
- src/components/BodyLogger.tsx
- src/hooks/useLogin.ts
- src/hooks/useRebuildI18n.ts
In this PR:
- a fix for users being redirected to logout while obtaining an auth token
- removed dead code
- refactored components into hooks
> PIN-1891: Hotfix for forced logout

- public/locales/en/attribute.json
- public/locales/en/eservice.json
- public/locales/it/attribute.json
- public/locales/it/eservice.json
- src/components/AttributeGroup.tsx
- src/components/AttributeSection.tsx
- src/components/BodyLogger.tsx
- src/components/EServiceCreateStep1General.tsx
- src/components/InformationRow.tsx
- src/components/Shared/AsyncTableEservice.tsx
- src/components/Shared/StyledInputControlledSelect.tsx
- src/components/Shared/StyledSection.tsx
- src/lib/constants.ts
- src/lib/env.ts
- src/lib/eservice-utils.ts
- src/views/AgreementEdit.tsx
- src/views/EServiceManage.tsx
- types.ts
- Rewritten and redesigned ([figma](https://www.figma.com/file/94inRFutOqSgK1Gj5M0FCr/Interop-%E2%80%94-v0.5-Raffinamento-per-prod-%5BWIP%5D?node-id=2175%3A49675)) EServiceManage component from the ground up.
- Page now scrolls to the top on location.pathname change.
- Added WELL_KNOWN_URL environment variable
- Added InformationRow component
- Fixed some spacing inconsistencies in StyledSection and AttributeSection
- Added utility function "getLatestActiveVersion" that, given an array of descriptors, returns the active one
> Pin 1704 - Redesign UI e-service details

- public/locales/en/agreement.json
- public/locales/en/eservice.json
- public/locales/it/agreement.json
- public/locales/it/eservice.json
- src/components/AttributeGroup.tsx
- src/components/Shared/DownloadableDocumentListSection.tsx
- src/components/Shared/EServiceContentInfo.tsx
- src/components/Shared/StyledAccordion.tsx
- src/lib/attributes.ts
- src/views/AgreementEdit.tsx
- src/views/AgreementRead.tsx
Including agreement upgrade. Missing in this PR are the new agreement states and the integration with the backend, handled in [PIN-2000](https://pagopa.atlassian.net/browse/PIN-2000)
> PIN-1842: design update to agreement view and manage

- src/lib/attributes.ts
This PR filters out the empty attributes group from the e-service draft payload, avoiding confusing UI error
> Pin 2024 - Remove empty attribute groups from create e-service draft payload 

- src/App.tsx
Commented MixPanel and OneTouch's Initialization code in `App.tsx`
> PIN-2031 - Removed MixPanel & OneTouch initialization code

- src/components/Footer.tsx
- src/components/FooterWrapper.tsx
- added footer links
- temp replaced footer with bugs so that links work properly
> Pin 2049 - Footer links

- src/components/EServiceCreateStep3DocumentsInterface.tsx
This PR contains a fix to the download error of an uploaded e-service interface.
> PIN-2066 - Fixed error download interface

- public/locales/en/purpose.json
- public/locales/it/purpose.json
- src/components/Shared/StyledRiskAnalysisSwitch.tsx
- src/data/risk-analysis/pa/v2.0.json
- src/hooks/useDynamicRiskAnalysisForm.tsx
- Normalized logic between backend and frontend.
- Added _required_, _max length_ and _multiple choice_ dynamic labels to risk analysis input.
> Pin 1931 - Updated risk analysis v2.0

- .github/ISSUE_TEMPLATE/.workflows/sonar-build-spec.yml
- package-lock.json
- package.json
- setupTests.js
- src/api/comon.api.types.ts
- src/api/react-query-wrappers/index.ts
- src/api/react-query-wrappers/useMutationWrapper.ts
- src/api/react-query-wrappers/useQueryWrapper.ts
- src/hooks/useCheckSessionExpired.ts
- tsconfig.json
- vite.config.ts
> [PIN-2368] Setup testing and sonarcloud intergration

- .github/workflows/ci.yml
- .github/workflows/clean.yml
- package.json
I enabled the CI on GH actions, enjoy
> Moving Continuous Integration on GH Actions

- src/components/shared/EServiceDetails/EServiceDetails.tsx
- src/components/shared/EServiceDetails/components/EServiceProviderContacts.tsx
- src/static/locales/en/eservice.json
- src/static/locales/it/eservice.json
- src/types/eservice.types.ts
This PR adds the contact section to the consumer e-service details page.
> [PIN-1960] Added contact mail to consumer e-service details page

- src/components/layout/Header.tsx
- src/config/constants.ts
This PR adds the missing header links for documentation and assistance.
> [PIN-2639] - Fix header links

- src/api/agreement/agreement.hooks.ts
- src/api/agreement/agreement.services.ts
- src/hooks/useGetAgreementsActions.ts
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/mutations-feedback.json
- Implemented service clone agreement
- Implemented hook to use the clone agreement service
- Implemented clone action
- Little refactor for agreement actions (define the actions in variables first)
- Added toast and dialog strings
> [PIN - 2662] - Clone agreement

- setupTests.js
- src/api/purpose/purpose.hooks.ts
- src/pages/ConsumerEServiceCatalogPage/components/CatalogCard.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceAutocomplete.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceForm.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateRiskAnalysisPreview.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateTemplateAutocomplete.tsx
- src/static/locales/en/purpose.json
- src/static/locales/it/purpose.json
- Added back purpose template selection ;
- Silenced logs in tests.
> [PIN-2691] - Purpose template selection

- src/api/agreement/agreement.hooks.ts
- src/components/dialogs/DialogAttributeDetails.tsx
- src/components/dialogs/DialogCreateNewAttribute.tsx
- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
This PR removes the origin and code attributes field in reading and writing.
> [PIN-2757] - Removed origin and code attributes fields

- src/components/dialogs/DialogRejectAgreement.tsx
- src/pages/ConsumerAgreementCreatePage/components/ConsumerNotesInputSection.tsx
- src/pages/ConsumerAgreementDetailsPage/ConsumerAgreementDetails.page.tsx
- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
- Fixed consumerNotes value disappearing on agreement re-fetch;
- Added minimum character requirement to reject agreement reason field;
- Fixed a crash on agreement details page reload
> [PIN-2761] - Bug fixing test release

- src/api/eservice/eservice.services.ts
- src/hooks/__tests__/useGetProviderEServiceActions.test.ts
- src/hooks/useGetProviderEServiceActions.ts
Reverted back to CATALOG process the following services:
- `/eservices`
- `/eservices/{eserviceId}`
> [PIN-2781] - Catalog process to BFF

- src/hooks/__tests__/useClientKind.test.ts
- src/utils/testing.utils.tsx
- Implemented tests for useClientKind hook
- Modified wrapper routes in testing.utils
> [PIN-2830] - Testing useClientKind hook

- __mocks__/data/client.mocks.ts
- src/hooks/__tests__/useGetClientActions.test.ts
- Added client mock function
- Modified routes for wrapper in testing.utils
- Implemented tests for useGetClientActions hook
> [PIN-2831] - Implemented test for useGetClientActions hook

- src/pages/ConsumerAgreementDetailsPage/ConsumerAgreementDetails.page.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceForm.tsx
- Added way to take default e-service for purpose creation from the url params;
- Added e-service url param to link to purpose creation in agreement details page.
> Feature: PIN-2882 - Added default e-service selection in purpose create

- src/pages/ConsumerEServiceCatalogPage/components/CatalogCard.tsx
- src/utils/common.utils.ts
- Update card catalog's actions to be always at the bottom;
- Added e-service description text truncation.
> Feature: PIN-2881 - Update CatalogCard component layout and e-service description text truncation

- src/api/purpose/purpose.hooks.ts
- src/api/purpose/purpose.services.ts
- src/hooks/__tests__/useGetAgreementsActions.test.ts
- src/hooks/__tests__/useGetConsumerPurposesActions.test.ts
- src/hooks/useGetConsumerPurposesActions.ts
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/mutations-feedback.json
- Added clone service and action inside `useGetConsumerPurposesActions`;
- updated `useGetConsumerPurposesActions tests.
> Feature: PIN-2814 -  BFF purpose clone

- src/api/client/client.services.ts
> [PIN - 2857] - frontend integration remove operator from client

- src/api/client/client.services.ts
> [PIN - 2855] - frontend integration client delete

- src/components/shared/Filters/FilterAutocompleteMultiple.tsx
- src/components/shared/Filters/FilterTextField.tsx
- src/components/shared/Filters/FiltersFields.tsx
- src/components/shared/react-hook-form-inputs/RHFAutocomplete/_RHFAutocompleteBase.tsx
- Added shadow on autocomplete's comboboxes;
- Added active filter icon button in filters single text fields.
> Feature: PIN-2789 - Filters components [2]

- src/api/purpose/purpose.services.ts
- src/pages/ConsumerPurposeEditPage/components/PurposeEditStep1General/PurposeEditStep1GeneralForm.tsx
> [PIN - 2824] - Frontend integration update purpose draft

- src/components/dialogs/DialogSessionExpired.tsx
- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
- Changed button type
- Changed label strings
> [PIN - 2845] - Changed button and strings in DialogSessionExpired

- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
Updated session expired description strings
> [PIN - 2846] - Updated session expired description

- src/components/layout/SideNav/SideNav.tsx
- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
- src/types/common.types.ts
- Added STAGE to PagoPAEnvVars type
- Update SideNav
- Updated strings label
> [PIN - 2892] - Upgrade groups and users in side nav

- src/api/client/client.services.ts
> [PIN - 2909] - Frontend integration get client operators

- src/api/purpose/purpose.services.ts
> [PIN - 2903] - Frontend integration add purpose on client

- src/api/client/client.services.ts
> [PIN - 2902] - Frontend integration add operator to client

- src/api/client/client.services.ts
> [PIN - 2901] - frontend integration post public key

- src/api/client/client.services.ts
> [PIN - 2899] - Frontend integration create client e-service

- src/api/party/party.api.types.ts
- src/api/party/party.hooks.ts
- src/api/party/party.services.ts
- src/components/layout/Header.tsx
- src/components/layout/SideNav/SideNav.tsx
- src/config/env.ts
This PR adds the following:
- Get user parties service;
- Available parties selector in header.
> Feature: PIN-2889 - Added selector in header

- src/api/client/client.api.types.ts
- src/api/client/client.hooks.ts
- src/api/client/client.services.ts
- src/components/dialogs/DialogAddClientToPurpose.tsx
- src/components/shared/ClientTable/ClientTable.tsx
- src/components/shared/ClientTable/ClientTableRow.tsx
- src/components/shared/CodeBlock.tsx
- src/hooks/useAutocompleteTextInput.ts
- src/hooks/useGetClientActions.ts
- src/pages/ConsumerClientListPage/ConsumerClientList.page.tsx
- src/pages/ConsumerClientM2MListPage/ConsumerClientM2MList.page.tsx
- src/static/locales/en/client.json
- src/static/locales/it/client.json
- src/types/client.types.ts
- Added `ClientListingItem` type;
- Updated client listing services;
- Set `skipThrowOn404Error` option to true in `ClientQueries.useGetList` query calls, waiting for PIN-3149 BE resolution;
- Added pagination and name filter to client table.
> Feature: PIN-2914 - BFF migration GET /clients

- __mocks__/data/client.mocks.ts
- src/api/client/client.services.ts
- src/pages/ConsumerClientManagePage/components/VoucherInstructions/ClientVoucherIntructionsPurposeSelect.tsx
- src/types/client.types.ts
- Updated `Client` type
- Changed get single client service base path to BFF
> Feature: PIN-2921 - Updated get single client to BFF

- src/components/layout/Header.tsx
Also:
- Updated selfcare dashboard redirect url.
> Fix: Product not switching on first click

- src/api/auth/auth.hooks.ts
- src/api/auth/auth.services.ts
- src/config/env.ts
- src/router/components/RoutesWrapper/AuthGuard.tsx
This PR adds a service in `auth.services`, `getBlacklist`.
The `AuthGuard` throws an `AuthorizationError` if the active user is inside the blacklist.
> Feature: PIN-3228 - Blacklist check

- src/hooks/__tests__/useGetEServiceConsumerActions.test.ts
- src/hooks/useGetEServiceConsumerActions.ts
- src/pages/ConsumerEServiceCatalogPage/components/CatalogCard.tsx
- src/pages/ConsumerEServiceCatalogPage/components/__test__/CatalogCard.test.tsx
- src/pages/ConsumerEServiceCatalogPage/components/__test__/__snapshots__/CatalogCard.test.tsx.snap
- src/static/locales/en/common.json
- src/static/locales/en/eservice.json
- src/static/locales/it/common.json
- src/static/locales/it/eservice.json
- src/utils/__tests__/common.utils.test.tsx
- src/utils/common.utils.ts
- implemented new design
- added new strings
> [PIN - 3202] - Update design catalog cards

- __mocks__/data/attribute.mocks.ts
- src/api/api.generatedTypes.ts
- src/api/attribute/attribute.hooks.ts
- src/api/attribute/attribute.services.ts
- src/components/shared/EServiceDetails/components/EServiceAttributesSections.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/AddAttributesToEServiceForm.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/AttributeAutocomplete.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/AttributeGroup.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/__test__/AddAttributesToEServiceForm.test.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/__test__/AttributeAutocomplete.test.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/__test__/AttributeGroup.test.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/__test__/__snapshots__/AddAttributesToEServiceForm.test.tsx.snap
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/__test__/__snapshots__/AttributeAutocomplete.test.tsx.snap
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStep1General/AddAttributesToEServiceForm/__test__/__snapshots__/AttributeGroup.test.tsx.snap
- src/types/attribute.types.ts
Updated generatedTypes file
Updated service getList (/attributes) and hook getList adding new types.
Updated AttributeAutocomplete components
> [PIN - 2964] - Attributes listing integration

- src/App.tsx
- src/api/maintenance/index.ts
- src/api/maintenance/maintenance.hooks.ts
- src/api/maintenance/maintenance.services.ts
- src/components/shared/MaintenanceBanner.tsx
- src/components/shared/__tests__/MaintenanceBanner.test.tsx
- src/components/shared/__tests__/__snapshots__/MaintenanceBanner.test.tsx.snap
- src/hooks/__tests__/useMaintenanceBanner.test.ts
- src/hooks/useMaintenanceBanner.ts
- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
- Implemented `MaintenanceBanner` component that show if there is a maintenance incoming
- Implemented `useMaintenanceBanner` hook that contain the logic to manage maintenance data fetched and to show or not the `MaintenanceBanner`
- Implemented tests for `MaintenanceBanner` and `useMaintenanceBanner`
> Feature: PIN - 3205 - Maintenance banner

- src/router/routes.tsx
Reverts pagopa/pdnd-interop-frontend#440
> Revert "Feature: basepath fix"

- src/api/maintenance/maintenance.hooks.ts
Reverts pagopa/pdnd-interop-frontend#439
> Revert "Feature: attempt fix dev CORS Error crash"

- vite.config.ts
Reverts pagopa/pdnd-interop-frontend#441
> Revert "Feature: Added sourcemaps in prod"

- __mocks__/data/client.mocks.ts
- __mocks__/data/purpose.mocks.ts
- src/api/api.generatedTypes.ts
- src/api/purpose/purpose.hooks.ts
- src/api/purpose/purpose.services.ts
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceForm.tsx
- src/pages/ConsumerPurposesListPage/ConsumerPurposesList.page.tsx
- src/pages/ProviderPurposesListPage/ProviderPurposesList.page.tsx
This PR updates the generated api types with the `npm run generate-types` command.
Various type fixes.
> Feature: Type sync

- src/api/agreement/agreement.hooks.ts
- src/api/agreement/agreement.services.ts
- src/hooks/__tests__/useGetEServiceConsumerActions.test.ts
- src/hooks/useGetEServiceConsumerActions.ts
- src/pages/ConsumerEServiceCatalogPage/components/CatalogCard.tsx
- src/pages/ConsumerEServiceDetailsPage/ConsumerEServiceDetails.page.tsx
- src/pages/ConsumerEServiceDetailsPage/components/ConsumerEServiceDetailsAlerts.tsx
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/mutations-feedback.json
- src/utils/__tests__/agreement.utils.test.ts
- src/utils/agreement.utils.ts
Also:
- Added new agreement utility functions;
- Added new `createAndSubmitDraft` service;
- Moved consumer e-service details alert into a separate component.
> Feature: PIN-2939 - Directly submit agreement if subscriber is owner of the eservice

- src/components/shared/AgreementDetails/AgreementDetailsContext.tsx
- src/components/shared/AgreementDetails/components/AgreementAttributesListSections/AgreementVerifiedAttributesDrawer/AgreementVerifiedAttributesDrawer.tsx
- src/components/shared/AgreementDetails/components/AgreementAttributesListSections/AgreementVerifiedAttributesDrawer/__tests__/AgreementVerifiedAttributesDrawer.test.tsx
- src/components/shared/AgreementDetails/components/AgreementAttributesListSections/AgreementVerifiedAttributesSection.tsx
- src/components/shared/AgreementDetails/components/AgreementAttributesListSections/__tests__/AgreementVerifiedAttributesSection.test.tsx
- src/components/shared/AgreementDetails/hooks/__tests__/useAgreementGetVerifiedAttributesActions.test.ts
- src/components/shared/AgreementDetails/hooks/useAgreementGetVerifiedAttributesActions.ts
- Fixed missing drawer animation;
- Added close behaviour after update/verify/revoke mutations;
- Code reformat;
- Updated tests.
> Feature: Agreement verified attributes drawer

- src/components/shared/AgreementDetails/components/AgreementAttributesListSections/AgreementVerifiedAttributesSection.tsx
- src/components/shared/AgreementDetails/components/AgreementAttributesListSections/__tests__/__snapshots__/AgreementVerifiedAttributesSection.test.tsx.snap
- src/components/shared/AgreementDetails/hooks/__tests__/useAgreementGetVerifiedAttributesActions.test.ts
- src/components/shared/AgreementDetails/hooks/useAgreementGetVerifiedAttributesActions.ts
- src/hooks/useDescriptorAttributesPartyOwnership.ts
- src/pages/PartyRegistryPage/components/PartyAttributesSection/PartyAttributesSection.tsx
- src/pages/PartyRegistryPage/components/PartyAttributesSection/VerifiedPartyAttributes.tsx
- src/utils/__tests__/attribute.utils.test.ts
- src/utils/attribute.utils.ts
- Updated verified (`isAttributeOwned`) and revoked (`isAttributeRevoked`) logic functions
- Updated tests and snaps
- Implemented double list item when attribute is both verified and revoked in `VerifiedPartyAttributes`
> Bugfix: PIN-3670 - Fix verified and revoked attributes

- package-lock.json
- package.json
- src/router/routes.tsx
Bumped interop commons to `1.3.0` and adapted the router to the new router implementation
> Feature: Update interop common router

- __mocks__/data/agreement.mocks.ts
- __mocks__/data/purpose.mocks.ts
- package-lock.json
- src/api/api.generatedTypes.ts
- src/api/purpose/purpose.hooks.ts
- src/api/purpose/purpose.services.ts
- src/pages/ConsumerClientCreatePage/ConsumerClientCreate.page.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceAutocomplete.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceForm.tsx
- src/pages/ConsumerPurposeEditPage/components/PurposeEditStep1General/PurposeEditStep1GeneralForm.tsx
- src/pages/ConsumerPurposeEditPage/components/PurposeEditStep2RiskAnalysis/PurposeEditStep2RiskAnalysis.tsx
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/mutations-feedback.json
- Updated `generatedTypes`
- Updated `createClient` calls removing `addOperators` waterfall call
- Removed `createVersionDraft` service and `useCreateVersionDraft` hook and its strings
- Updated `createPurposeDraft` call removing `createVersionDraft` waterfall call
- Updated mocks
- Removed `updateDraftVersion` waterfall call from `updateDraft` in create purpose
> Feature: PIN-3764 - updating client and purpose calls

- src/components/layout/SideNav/__tests__/__snapshots__/SideNav.test.tsx.snap
- src/components/layout/SideNav/hooks/__tests__/useGetSideNavItems.test.ts
- src/pages/ConsumerClientCreatePage/ConsumerClientCreate.page.tsx
- src/pages/ConsumerClientCreatePage/components/OperatorsInputTable.tsx
- src/router/routes.tsx
- src/static/locales/en/client.json
- src/static/locales/it/client.json
- src/static/locales/it/shared-components.json
- Updated strings
- Updated `ConsumerClientCreate` page
- Removed `SideNav` from `ConsumerClientCreate` page
- Modified delete button in `OperatorsInputTable`
> Feature: PIN-3623 - create client redesign

- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceForm.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateProviderRiskAnalysis.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateProviderRiskAnalysisAutocomplete.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepPurpose/EServiceCreateStepPurpose.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepPurpose/EServiceCreateStepPurposeAddPurposesTable.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepPurpose/EServiceCreateStepPurposeRiskAnalysis/EServiceCreateStepPurposeRiskAnalysisForm.tsx
- src/pages/ProviderEServiceSummaryPage/ProviderEServiceSummary.page.tsx
- src/pages/ProviderEServiceSummaryPage/components/ProviderEServiceRiskAnalysisSummary.tsx
- src/pages/ProviderEServiceSummaryPage/components/ProviderEServiceRiskAnalysisSummaryList.tsx
- src/static/locales/en/eservice.json
- src/static/locales/en/purpose.json
- src/static/locales/it/eservice.json
- src/static/locales/it/mutations-feedback.json
- src/static/locales/it/purpose.json
> Feature: PIN-3980 - Strings reverse delivery

- src/api/auth/auth.services.ts
- src/components/shared/EServiceVersionSelectorDrawer.tsx
Reverts pagopa/pdnd-interop-frontend#607
> Revert "Feature: Fix selfcare token not removing from hash and wrong redirect on e-service version selection"

- package-lock.json
- src/api/api.generatedTypes.ts
- src/components/layout/Header.tsx
- src/types/party.types.ts
- Added parentName in partyItem
- Added routeParent field in jwt type
- Updated generatedTypes
- Updated package-lock
> Feature: PIN-3657 - AOO/UO parent name management in party switch

- __mocks__/data/key.mocks.ts
- __mocks__/data/purpose.mocks.ts
- __mocks__/data/user.mocks.ts
- src/api/api.generatedTypes.ts
- src/api/client/client.hooks.ts
- src/api/client/client.services.ts
- src/api/party/party.hooks.ts
- src/api/party/party.services.ts
- src/components/dialogs/DialogRemoveOperatorFromClient.tsx
- src/components/shared/AddOperatorsToClientDrawer.tsx
- src/components/shared/StatusChip.tsx
- src/hooks/useGetClientOperatorsActions.ts
- src/pages/ConsumerClientCreatePage/ConsumerClientCreate.page.tsx
- src/pages/ConsumerClientCreatePage/components/OperatorsInputTable.tsx
- src/pages/ConsumerClientManagePage/components/ClientOperators/ClientOperators.tsx
- src/pages/ConsumerClientManagePage/components/ClientOperators/ClientOperatorsTable.tsx
- src/pages/ConsumerClientManagePage/components/ClientOperators/ClientOperatorsTableRow.tsx
- src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientAddPublicKeyButton.tsx
- src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientPublicKeys.tsx
- src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientPublicKeysTableRow.tsx
- src/pages/KeyDetailsPage/components/KeyGeneralInfoSection.tsx
- src/pages/OperatorDetailsPage/components/OperatorGeneralInfoSection.tsx
- src/pages/PartyRegistryPage/components/PartyContactsSection/UpdatePartyMailDrawer.tsx
- src/static/locales/en/user.json
- src/static/locales/it/user.json
- src/types/dialog.types.ts
- Updated `api.generatedTypes`
- Updated services and hooks to use new types and paths
- Updated components to use new types
> Feature: PIN-3521 - Selfcare API V2 migration

- src/static/locales/en/voucher.json
- src/static/locales/it/voucher.json
- Added string associated to error code key
> Feature: PIN-3867 - Added new debug voucher error

- src/config/env.ts
- src/pages/PartyRegistryPage/PartyRegistry.page.tsx
- src/pages/PartyRegistryPage/components/PartyGeneralInfoSection/PartyGeneralInfoSection.tsx
- src/pages/PartyRegistryPage/components/PartyGeneralInfoSection/index.ts
- src/static/locales/en/party.json
- src/static/locales/it/party.json
Created general info section.
the `digitalAddress` field is not present in the current implementation. This omission is intentional.
> General information card

- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepVersion/EServiceCreateStepVersion.tsx
The default is now automatic approval. This is already the default on the backend
> Changed Agreement approval policy default

- src/components/layout/SideNav/hooks/useGetSideNavItems.ts
- src/pages/TenantCertifierPage/components/AssignAttributesTab/AssignAttributeDrawer.tsx
- src/pages/TenantCertifierPage/components/ManageAttributesTab/ManageAttributesTab.tsx
In this PR has been added optional chaining check on certifierId  in order to avoid error if logged user is not a certifier.
> PIN-4529 - Check if user is a certifier

- package.json
- src/hooks/useGetProviderEServiceActions.ts
When we create the draft of a new e-service version, the default policy for the agreements approval should be `AUTOMATIC`
> Hotfix/PIN-4564: Manual to automatic approval policy

- src/pages/PartyRegistryPage/components/PartyAttributesSection/CertifiedPartyAttributes.tsx
- src/static/locales/en/attribute.json
- src/static/locales/it/attribute.json
Check if the certified attributes are revoked and shows the right chip
> PIN-4449: Show revoked certificate attribute 

- src/api/auth/auth.utils.ts
- src/components/layout/SideNav/hooks/__tests__/useGetSideNavItems.test.ts
- src/components/layout/SideNav/hooks/useGetSideNavItems.ts
- src/config/env.ts
- src/router/components/RoutesWrapper/AuthGuard.tsx
- src/router/components/RoutesWrapper/RoutesWrapper.tsx
- src/router/components/RoutesWrapper/__tests__/AuthGuard.test.tsx
- src/types/common.types.ts
- src/utils/testing.utils.tsx
[To be merged after #752  ]
- Updated `PagoPAEnv` types
- Changed `isIPAOrganization` to `isOrganizationAllowedToProduce`
- Updated `env.ts`
> Feature: PIN-4576 - Add possibility to create eservice to private tenants

- src/utils/attribute.utils.ts
Fix `isAttributeRevoked` logic and `isAttributeOwned` logic for verified attributes
> Bugfix: PIN-4647 - Fix verified attribute revoked and owned logic

- src/pages/ProviderPurposeDetailsPage/ProviderPurposeDetails.page.tsx
- src/pages/ProviderPurposeDetailsPage/components/ProviderPurposeDetailsDailyCallsPlanCard.tsx
- src/static/locales/en/purpose.json
- src/static/locales/it/purpose.json
- New card design
- Changed alert dimension
> Feature: PIN-4615 - New plan card (provider) design

- src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientAddPublicKeyButton.tsx
- src/static/locales/en/key.json
- src/static/locales/it/key.json
- implemented new enable logic (added limit to public keys number)
- added new tooltips
- added strings
> Feature: PIN-4150 - Implemented new check to enable addPublicKeyButton

- src/components/layout/containers/DocumentContainer.tsx
- src/components/layout/containers/__tests__/DocumentContainer.test.tsx
- src/components/layout/containers/__tests__/__snapshots__/DocumentContainer.test.tsx.snap
- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceDocumentationSection.tsx
- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceTechnicalInfoSection.tsx
- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceUpdateDocumentationDrawer.tsx
- src/static/locales/en/common.json
- src/static/locales/en/eservice.json
- src/static/locales/it/common.json
- src/static/locales/it/eservice.json
- Implemented new style for `DocumentContainer` and updated tests
- Implemented `ProviderEServiceUpdateDocumentationDrawer` and `ProviderEServiceDocumentationSection`
- Updated `ProviderEServiceTechnicalInfoSection` adding `ProviderEServiceDocumentationSection`
- Updated snapshots
> Feature: PIN-4910 - edit documentation

- src/api/api.generatedTypes.ts
- src/api/eservice/eservice.hooks.ts
- src/api/eservice/eservice.services.ts
- src/components/layout/containers/PageContainer.tsx
- src/components/layout/containers/__tests__/__snapshots__/PageContainer.test.tsx.snap
- src/components/shared/Drawer.tsx
- src/components/shared/__tests__/__snapshots__/Drawer.test.tsx.snap
- src/pages/ConsumerDebugVoucherPage/components/__test__/__snapshots__/DebugVoucherResults.test.tsx.snap
- src/pages/ConsumerDebugVoucherPage/components/__test__/__snapshots__/DebugVoucherStepDrawer.test.tsx.snap
- src/pages/ProviderEServiceListPage/ProviderEServiceList.page.tsx
- src/pages/ProviderEServiceListPage/components/ProviderEServiceImportVersionDrawer.tsx
- src/static/locales/en/common.json
- src/static/locales/en/eservice.json
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/common.json
- src/static/locales/it/eservice.json
- src/static/locales/it/mutations-feedback.json
[not merge, waiting fix on import service]
WIP - remove TODO, comment and console.log
- Updated api.generatedTypes
- Implemented importVersion service and hook
- Implemented ProviderEServiceImportVersionDrawer
- Added import version drawer to provider eservice list page
- Added tooltip to shared drawer component
- Changed Box with Stack "row" in top side action
> Feature: PIN-4921 - Import eservice

- src/components/shared/react-hook-form-inputs/RHFSwitch.tsx
- src/components/shared/react-hook-form-inputs/__tests__/RHFSwitch.test.tsx
- src/components/shared/react-hook-form-inputs/__tests__/__snapshots__/RHFSwitch.test.tsx.snap
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepVersion/EServiceCreateStepVersion.tsx
- src/utils/form.utils.ts
This PR update behavior on RHFSwitch. With this PR, the switch value change even if you click its description
> Feature: PIN-4646 - Update behavior onChange RHFSwitch

- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceUpdateDocumentationDrawer.tsx
- Update `ProviderEServiceUpdateDocumentationDrawer` to fix document pagination issues
> Feature: PIN-5028 - bug deleting document from documentation drawer

- src/api/api.generatedTypes.ts
- src/api/eservice/eservice.hooks.ts
- src/api/eservice/eservice.services.ts
- src/pages/PartyRegistryPage/components/PartyContactsSection/UpdatePartyMailDrawer.tsx
- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceGeneralInfoSection/ProviderEServiceGeneralInfoSection.tsx
- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceGeneralInfoSection/ProviderEServiceUpdateDescriptionDrawer.tsx
- src/pages/ProviderEServiceDetailsPage/components/ProviderEServiceTechnicalInfoSection/ProviderEServiceUpdateThresholdsDrawer.tsx
- src/static/locales/en/eservice.json
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/eservice.json
- src/static/locales/it/mutations-feedback.json
- Update `api.generatedTypes`
- Implemented new `service` and `hook`
- Implemented new `ProviderEServiceUpdateDescriptionDrawer`
- Changed `ProviderEServiceGeneralInfoSection` and added `ProviderEServiceUpdateDescriptionDrawer`
- fix reset form bug caused by eventual consistency
> Feature: PIN-5059 - Update eservice description

- src/components/shared/IconLink.tsx
- src/config/constants.ts
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepDocuments/EServiceCreateStepDocuments.tsx
- src/static/locales/en/eservice.json
- src/static/locales/it/eservice.json
- Added link to OpenAPI checker in e-service creation
- Edited IconLink so that on hover, the text is underlined
> Feature/PIN-5073: added link to OpenAPI checker

- src/hooks/useGetConsumerPurposesActions.ts
- src/pages/ConsumerPurposeSummaryPage/ConsumerPurposeSummary.page.tsx
- Fixed error in check for publish purpose (in `ConsumerPurposeSummary`)
- Added check for publish in `useGetConsumerPurposeActions`
> Feature: PIN-5291 fix check for publish error in consumer purpose summary

- src/components/layout/Footer.tsx
- src/router/components/RoutesWrapper/__tests__/__snapshots__/RoutesWrapper.test.tsx.snap
Updated link in footer for the new AgID accessibility declaration
> Feature: PIN-5300 - updated A11Y AgID declaration link

- src/components/shared/RiskAnalysisFormComponents/RiskAnalysisFormComponents.tsx
Updated validate rule for switch component
> Fix RiskAnalysis form

- scripts/open-api-type-generator.js
- src/api/api.generatedTypes.ts
- src/api/client/client.mutations.ts
- src/api/client/client.services.ts
- src/pages/ConsumerClientManagePage/components/ClientOperators/ClientOperators.tsx
- src/static/locales/en/mutations-feedback.json
- src/static/locales/it/mutations-feedback.json
- update generatedTypes and its script
- update service and mutation
- update operators tab
- update strings
> Feature: PIN-5340 - Add multiple user to client

- src/components/dialogs/Dialog.tsx
- src/components/dialogs/DialogRevokeProducerDelegation.tsx
- src/hooks/useGetDelegationActions.ts
- src/static/locales/en/shared-components.json
- src/static/locales/it/shared-components.json
- src/types/dialog.types.ts
[ merge after #999 ]
- Implemented revoke delegation dialog
- Update useGetDelegationActions
> Feature: PIN-5431 - Revoke delegation

- src/api/eservice/eservice.mutations.ts
- src/api/eservice/eservice.services.ts
- src/components/dialogs/Dialog.tsx
- src/components/dialogs/DialogRejectDelegatedVersionDraft.tsx
- src/components/layout/SideNav/hooks/__tests__/useGetSideNavItems.test.ts
- src/components/shared/StatusChip.tsx
- src/hooks/__tests__/useGetDelegationUserRole.test.ts
- src/hooks/__tests__/useGetProviderEServiceActions.test.ts
- src/hooks/useGetDelegationActions.ts
- src/hooks/useGetDelegationUserRole.ts
- src/hooks/useGetProviderEServiceActions.ts
- src/pages/ProviderEServiceDetailsPage/ProviderEServiceDetails.page.tsx
- src/pages/ProviderEServiceListPage/components/EServiceTableRow.tsx
- src/pages/ProviderEServiceSummaryPage/ProviderEServiceSummary.page.tsx
- src/static/locales/en/common.json
- src/static/locales/en/eservice.json
- src/static/locales/en/mutations-feedback.json
- src/static/locales/en/shared-components.json
- src/static/locales/it/common.json
- src/static/locales/it/eservice.json
- src/static/locales/it/mutations-feedback.json
- src/static/locales/it/shared-components.json
- src/types/dialog.types.ts
Implemented the management of eservice on delegation when the user is delegate and when is delegator
> Feature: PIN - 5702/5703 - E-service managed by delegation

- src/hooks/useGetAgreementsActions.ts
- src/hooks/useGetDelegationUserRole.ts
- src/hooks/useGetProviderPurposesActions.ts
- src/pages/DelegationDetailsPage/DelegationDetails.page.tsx
- fix purpose actions
- fix backToDelegationsList navigation
> Fix purpose actions

- src/pages/DelegationCreatePage/components/DelegationCreateCards.tsx
Hidden consumer delegation card
> Hidden consumer delegation card

- src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityDrawer.tsx
- src/pages/DelegationsPage/DelegationsAvailabilityTab/DelegationAvailabilityTab.tsx
Hidden consumer delegation availability
> fix-hide-consumer-delegation-availability

- src/api/delegation/delegation.mutations.ts
- src/api/delegation/delegation.services.ts
- src/pages/DelegationCreatePage/components/DelegationCreateCards.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateEServiceAutocomplete.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateForm.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateTenantAutocomplete.tsx
- src/static/locales/en/mutations-feedback.json
- src/static/locales/en/party.json
- src/static/locales/it/mutations-feedback.json
- src/static/locales/it/party.json
- Update `DelegationCreateCards`
> Feature: PIN-5824 - delegation create

- src/api/delegation/delegation.mutations.ts
- src/api/delegation/delegation.services.ts
- src/components/dialogs/Dialog.tsx
- src/components/dialogs/DialogAcceptDelegation.tsx
- src/components/dialogs/DialogRejectDelegation.tsx
- src/hooks/useGetDelegationActions.ts
- src/pages/DelegationsPage/components/DelegationsReceivedTab/DelegationsReceivedTab.tsx
- src/static/locales/en/mutations-feedback.json
- src/static/locales/en/shared-components.json
- src/static/locales/it/mutations-feedback.json
- src/static/locales/it/shared-components.json
- src/types/dialog.types.ts
- Implemented new services and mutations
- Update `DelegationsReceivedTab`X
- Update dialogs
- Update `useGetDelegationActions`
> Feature: PIN-5825 - accept and reject delegation

- src/api/delegation/delegation.mutations.ts
- src/api/delegation/delegation.services.ts
- src/components/dialogs/Dialog.tsx
- src/components/dialogs/DialogRevokeDelegation.tsx
- src/hooks/useGetDelegationActions.ts
- src/static/locales/en/mutations-feedback.json
- src/static/locales/en/shared-components.json
- src/static/locales/it/mutations-feedback.json
- src/static/locales/it/shared-components.json
- src/types/dialog.types.ts
- Implement new service and mutation
- Update `DialogRevokeProducerDelegation` to `DialogRevokeDelegation`
- Add strings
> Feature: PIN-5831 - Revoke delegation

- src/api/api.generatedTypes.ts
- src/components/dialogs/DialogCreateAgreementDraft/DialogCreateAgreementDraftAutocomplete.tsx
- src/components/dialogs/DialogRejectDelegation.tsx
- src/components/dialogs/DialogRevokeDelegation.tsx
- src/config/constants.ts
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateConsumerAutocomplete.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceAutocomplete.tsx
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateForm.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateCards.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateEServiceAutocomplete.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateForm.tsx
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepGeneral/EServiceCreateStepGeneral.tsx
- src/static/locales/en/party.json
- src/static/locales/en/shared-components.json
- src/static/locales/it/party.json
- src/static/locales/it/shared-components.json
- Fix spacing in `PurposeCreateForm`
- Fix spacing in `DialogRevokeDelegation`
- Add documentation links in `DialogRevokeDelegation` and `EServiceCreateStepGeneral`
- Fix strings
- Add submit button disable check in `DialogRejectDelegation`
- Fix autocomplete in `PurposeCreateForm`
- Update api.generatedTypes
> Feature: bug fixing

- src/components/dialogs/DialogCreateAgreementDraft/DialogCreateAgreementDraft.tsx
- src/components/shared/ByDelegationChip.tsx
- src/hooks/useGetConsumerPurposesActions.ts
- src/pages/ConsumerAgreementsListPage/components/ConsumerAgreementsTableRow.tsx
- src/pages/ConsumerPurposeDetailsPage/ConsumerPurposeDetails.page.tsx
- src/pages/ConsumerPurposeDetailsPage/components/PurposeDetailsTab/ConsumerPurposeDetailsDailyCallsPlanCard.tsx
- src/pages/ConsumerPurposeDetailsPage/components/PurposeDetailsTab/ConsumerPurposeDetailsDailyCallsUpdatePlanCard.tsx
- src/pages/DelegationCreatePage/components/DelegationCreateForm.tsx
- src/pages/ProviderAgreementsListPage/components/ProviderAgreementsTableRow.tsx
- Fix spacing in `ByDelegationChip`
- Fix bug - delegator can view purpose actions
- Fix bug - access purpose client tab
- Fix bug - delegator can request change plan
- Fix bug - delegator can delete change plan request
- Fix bug 6193 - delegate can't create agreement with new delegation after one was revoked
- Fix bug 6195 - alert message priority in delegation create
> Feature: PIN-6188-6189-6193-6195 - Fix

- package.json
- src/api/api.generatedTypes.ts
- src/api/client/client.services.ts
- src/pages/ConsumerClientManagePage/components/ClientPublicKeys/ClientAddPublicKeyDrawer.tsx
* Update api.generatedTypes.ts
* update service
> att: Release/1.1.11

- package-lock.json
- package.json
- src/api/auth/auth.utils.ts
- src/utils/__tests__/format.utils.test.ts
* Fix decode jwt and Bump version
* Skip bugged test
> Hotfix: Fix decode jwt and Bump version (#1185)

- src/components/layout/SideNav/hooks/__tests__/useGetSideNavItems.test.ts
- src/components/layout/SideNav/hooks/useGetSideNavItems.ts
- src/pages/ProviderEServiceCreatePage/components/EServiceCreateStepGeneral/EServiceCreateStepGeneral.tsx
- src/pages/ProviderEServiceSummaryPage/components/ProviderEServiceGeneralInfoSummary.tsx
- src/router/components/RoutesWrapper/AuthGuard.tsx
* Refactor: changed check from isPA to isOrganizationAllowedToView
* Fixed check
* Refactor: test for delegation section in sidenav
* Removed comment + edit strings in useGetSideNavItems.test
* Added check on eservice create form
> att: release/1.1.14

- vite.config.ts
This PR update` vite.config.ts` file to avoid CORS error on DEV env
> Update vite.config with proxy configuration

- src/components/layout/SideNav/hooks/__tests__/useGetSideNavItems.test.ts
- src/components/layout/SideNav/hooks/useGetSideNavItems.ts
- src/components/shared/CreateStepPurposeRiskAnalysisForm.tsx
- src/components/shared/RiskAnalysisFormComponents/RiskAnalysisFormComponents.tsx
- src/components/shared/RiskAnalysisFormComponents/RiskAnalysisSwitch.tsx
- src/components/shared/RiskAnalysisFormComponents/types/risk-analysis-form.types.ts
- src/config/react-i18next.ts
- src/hooks/useRiskAnalysisForm.ts
- src/pages/ConsumerPurposeEditPage/components/PurposeEditStepRiskAnalysis/RiskAnalysisForm/RiskAnalysisForm.tsx
- src/pages/DeveloperToolsPage/DeveloperTools.page.tsx
- src/pages/DeveloperToolsPage/index.ts
- src/pages/ProviderEServiceTemplateCreatePage/components/EServiceTemplateCreateStepPurpose/EServiceTemplateCreateStepPurposeRiskAnalysis/EServiceTemplateCreateStepPurposeRiskAnalysis.tsx
- src/pages/RiskAnalysisExporterToolPage/RiskAnalysisExporterTool.page.tsx
- src/pages/RiskAnalysisExporterToolPage/components/RiskAnalysisExporterToolContext.tsx
- src/pages/RiskAnalysisExporterToolPage/components/RiskAnalysisToolFormStep.tsx
- src/pages/RiskAnalysisExporterToolPage/components/RiskAnalysisToolJsonExportStep.tsx
- src/pages/RiskAnalysisExporterToolPage/index.ts
- src/pages/index.ts
- src/react-i18next.d.ts
- src/router/routes.tsx
- src/static/locales/en/common.json
- src/static/locales/en/developer-tools.json
- src/static/locales/en/shared-components.json
- src/static/locales/it/common.json
- src/static/locales/it/developer-tools.json
- src/static/locales/it/shared-components.json
- src/types/risk-analysis-form.types.ts
- src/utils/__tests__/risk-analysis-form.utils.test.ts
- src/utils/risk-analysis-form.utils.ts
Closes [PIN-6879](https://pagopa.atlassian.net/browse/PIN-6879)
[PIN-6879]: https://pagopa.atlassian.net/browse/PIN-6879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIN-6879 - Risk analysis exporter tool

- src/pages/DeveloperToolsPage/DeveloperTools.page.tsx
- src/static/locales/en/developer-tools.json
- src/static/locales/it/developer-tools.json
- src/utils/__tests__/risk-analysis-form.utils.test.ts
- src/utils/risk-analysis-form.utils.ts
Closes [PIN-6949](https://pagopa.atlassian.net/browse/PIN-6949?atlOrigin=eyJpIjoiZTcwNWU3ZGM0NDVhNDcyNzhlNWZiM2VjNjQwY2NkOGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
Closes [PIN-6950](https://pagopa.atlassian.net/browse/PIN-6950?atlOrigin=eyJpIjoiMzhhMDc3N2MxOWEyNGY1N2I2ZGJhYWI0OTM0MTg3YzkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
Removed `getFrontendAnswerValue` since with the fix would could be translated in `question.visualType === 'checkbox' ? answer : answer[0]`.
[PIN-6949]: https://pagopa.atlassian.net/browse/PIN-6949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIN-6950]: https://pagopa.atlassian.net/browse/PIN-6950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIN-6949] [PIN-6950] - Fix risk analysis tool form bugs

- maintenance-page/maintenance-standard.html
> vapt/PIN-6349: missing-integrity-attribute

- src/hooks/__tests__/useActiveTab.test.tsx
- src/hooks/useActiveTab.ts
TODO before merger
Update tests
> Hotfix: PIN-7356 - fix pagination offset when the tab is changed

- package.json
- src/pages/ConsumerPurposeCreatePage/components/PurposeCreateEServiceAutocomplete.tsx
PIN-7443: Temporarily increased to 200 the limit of e-services
> main:release/1.2.8 
